jobs:
- job: Ubuntu_MATLAB
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
#    - checkout: self
#      fetchDepth: 1
    - task: RunMATLABCommand@0
      inputs:
        command: 'results = runtests, assertSuccess(results);'
